using System;
using System.Collections.Generic;

#nullable disable

namespace NWC_Dashboard.Models
{
    public partial class Projectx
    {
        public int ProjId { get; set; }
        public decimal? Annualdiscountrate { get; set; }
        public DateTime? Anticipatedfinishdate { get; set; }
        public DateTime? Anticipatedstartdate { get; set; }
        public string Containssummarydata { get; set; }
        public decimal? Currentbudget { get; set; }
        public decimal? Currentvariance { get; set; }
        public DateTime? Datadate { get; set; }
        public string Discountapplicationperiod { get; set; }
        public decimal? Distributedcurrentbudget { get; set; }
        public string Earnedvaluecomputetype { get; set; }
        public string Earnedvalueetccomputetype { get; set; }
        public decimal? Earnedvalueetcuservalue { get; set; }
        public decimal? Earnedvalueuserpercent { get; set; }
        public DateTime? Finishdate { get; set; }
        public DateTime? Forecastfinishdate { get; set; }
        public DateTime? Forecaststartdate { get; set; }
        public decimal? Independentetclaborunits { get; set; }
        public decimal? Independentetctotalcost { get; set; }
        public string Name { get; set; }
        public string Obsname { get; set; }
        public int? Obsobjectid { get; set; }
        public decimal? Originalbudget { get; set; }
        public decimal? Overallprojectscore { get; set; }
        public int? Parentepsobjectid { get; set; }
        public decimal? Proposedbudget { get; set; }
        public string Risklevel { get; set; }
        public int? Riskscore { get; set; }
        public decimal? Riskexposure { get; set; }
        public DateTime? Startdate { get; set; }
        public string Status { get; set; }
        public decimal? Sumaccountingvarbylaborunits { get; set; }
        public decimal? Sumaccountingvariancebycost { get; set; }
        public decimal? Sumactthisperiodmaterialcost { get; set; }
        public decimal? Sumactthisperiodnonlaborcost { get; set; }
        public decimal? Sumactthisperiodnonlaborunits { get; set; }
        public decimal? Sumactualthisperiodlaborcost { get; set; }
        public decimal? Sumactualthisperiodlaborunits { get; set; }
        public decimal? Sumatcompletionmaterialcost { get; set; }
        public decimal? Sumatcompletionnonlaborcost { get; set; }
        public decimal? Sumatcompletionnonlaborunits { get; set; }
        public decimal? Sumatcompletiontotalcostvar { get; set; }
        public decimal? Sumbaselinecompactivitycount { get; set; }
        public decimal? Sumbaselinenotstartedactcnt { get; set; }
        public decimal? Sumblinprogressactivitycount { get; set; }
        public decimal? Sumbudgetatcmpbylaborunits { get; set; }
        public decimal? Sumbudgetatcompletionbycost { get; set; }
        public decimal? Sumcostperfindexbycost { get; set; }
        public decimal? Sumcostperfindexbylaborunits { get; set; }
        public decimal? Sumcostvariancebylaborunits { get; set; }
        public decimal? Sumcostvarindexbylaborunits { get; set; }
        public decimal? Sumdurationpercentofplanned { get; set; }
        public decimal? Sumeacbycost { get; set; }
        public decimal? Sumeacbylaborunits { get; set; }
        public decimal? Sumeachighpctbylaborunits { get; set; }
        public decimal? Sumeaclowpctbylaborunits { get; set; }
        public decimal? Sumetcbycost { get; set; }
        public decimal? Sumetcbylaborunits { get; set; }
        public decimal? Sumexpensecostpctcomplete { get; set; }
        public decimal? Sumlaborcostpercentcomplete { get; set; }
        public decimal? Sumlaborunitspercentcomplete { get; set; }
        public decimal? Sumactivitycount { get; set; }
        public decimal? Sumactualduration { get; set; }
        public decimal? Sumactualexpensecost { get; set; }
        public DateTime? Sumactualfinishdate { get; set; }
        public DateTime? Summaxactualfinishdate { get; set; }
        public DateTime? Summaxrestartdate { get; set; }
        public decimal? Sumactuallaborcost { get; set; }
        public decimal? Sumactuallaborunits { get; set; }
        public decimal? Sumactualmaterialcost { get; set; }
        public decimal? Sumactualnonlaborcost { get; set; }
        public decimal? Sumactualnonlaborunits { get; set; }
        public DateTime? Sumactualstartdate { get; set; }
        public decimal? Sumactualthisperiodcost { get; set; }
        public decimal? Sumactualtotalcost { get; set; }
        public decimal? Sumactualvaluebycost { get; set; }
        public decimal? Sumactualvaluebylaborunits { get; set; }
        public decimal? Sumatcompletionduration { get; set; }
        public decimal? Sumatcompletionexpensecost { get; set; }
        public decimal? Sumatcompletionlaborcost { get; set; }
        public decimal? Sumatcompletionlaborunits { get; set; }
        public decimal? Sumatcompletiontotalcost { get; set; }
        public decimal? Sumbaselineduration { get; set; }
        public decimal? Sumbaselineexpensecost { get; set; }
        public DateTime? Sumbaselinefinishdate { get; set; }
        public decimal? Sumbaselinelaborcost { get; set; }
        public decimal? Sumbaselinelaborunits { get; set; }
        public decimal? Sumbaselinematerialcost { get; set; }
        public decimal? Sumbaselinenonlaborcost { get; set; }
        public decimal? Sumbaselinenonlaborunits { get; set; }
        public DateTime? Sumbaselinestartdate { get; set; }
        public decimal? Sumbaselinetotalcost { get; set; }
        public decimal? Sumcompletedactivitycount { get; set; }
        public decimal? Sumcostpercentcomplete { get; set; }
        public decimal? Sumcostpercentofplanned { get; set; }
        public decimal? Sumcostvariancebycost { get; set; }
        public decimal? Sumcostvarianceindex { get; set; }
        public decimal? Sumcostvarianceindexbycost { get; set; }
        public decimal? Sumdurationpercentcomplete { get; set; }
        public decimal? Sumdurationvariance { get; set; }
        public decimal? Sumearnedvaluebycost { get; set; }
        public decimal? Sumearnedvaluebylaborunits { get; set; }
        public decimal? Sumexpensecostvariance { get; set; }
        public decimal? Sumfinishdatevariance { get; set; }
        public decimal? Suminprogressactivitycount { get; set; }
        public decimal? Sumlaborcostvariance { get; set; }
        public decimal? Sumlaborunitsvariance { get; set; }
        public decimal? Summaterialcostvariance { get; set; }
        public decimal? Sumnonlaborcostvariance { get; set; }
        public decimal? Sumnonlaborunitsvariance { get; set; }
        public decimal? Sumnotstartedactivitycount { get; set; }
        public decimal? Sumplannedvaluebycost { get; set; }
        public DateTime? Sumprogressfinishdate { get; set; }
        public decimal? Sumremainingduration { get; set; }
        public decimal? Sumremainingexpensecost { get; set; }
        public DateTime? Sumremainingfinishdate { get; set; }
        public decimal? Sumremaininglaborcost { get; set; }
        public decimal? Sumremaininglaborunits { get; set; }
        public decimal? Sumremainingmaterialcost { get; set; }
        public decimal? Sumremainingnonlaborcost { get; set; }
        public decimal? Sumremainingnonlaborunits { get; set; }
        public DateTime? Sumremainingstartdate { get; set; }
        public decimal? Sumremainingtotalcost { get; set; }
        public decimal? Sumschedulepercentcomplete { get; set; }
        public decimal? Sumperformancepercentcomplete { get; set; }
        public decimal? Sumschedulevariancebycost { get; set; }
        public decimal? Sumschedulevarianceindex { get; set; }
        public decimal? Sumstartdatevariance { get; set; }
        public decimal? Sumtotalcostvariance { get; set; }
        public decimal? Sumtotalfloat { get; set; }
        public decimal? Sumunitspercentcomplete { get; set; }
        public decimal? Summaterialcostpctcomplete { get; set; }
        public decimal? Sumnonlaborcostpctcomplete { get; set; }
        public decimal? Sumnonlaborunitspctcomplete { get; set; }
        public decimal? Sumperfpctcmpbylaborunits { get; set; }
        public decimal? Sumplannedvaluebylaborunits { get; set; }
        public decimal? Sumschdpctcmpbylaborunits { get; set; }
        public decimal? Sumschdperfindexbylaborunits { get; set; }
        public decimal? Sumschdvariancebylaborunits { get; set; }
        public decimal? Sumschdvarianceindexbycost { get; set; }
        public decimal? Sumschdvarindexbylaborunits { get; set; }
        public decimal? Sumscheduleperfindexbycost { get; set; }
        public decimal? Sumtocompleteperfindexbycost { get; set; }
        public decimal? Sumvaratcmpbylaborunits { get; set; }
        public DateTime? Sumearlystartdate { get; set; }
        public DateTime? Sumearlyenddate { get; set; }
        public DateTime? Sumlatestartdate { get; set; }
        public DateTime? Sumlateenddate { get; set; }
        public decimal? Summaxcalendarid { get; set; }
        public decimal? Summincalendarid { get; set; }
        public decimal? Totalbenefitplan { get; set; }
        public decimal? Totalbenefitplantally { get; set; }
        public decimal? Totalfunding { get; set; }
        public decimal? Totalspendingplan { get; set; }
        public decimal? Totalspendingplantally { get; set; }
        public decimal? Unallocatedbudget { get; set; }
        public decimal? Undistributedcurrentvariance { get; set; }
        public DateTime? Sumactualprogressdate { get; set; }
        public decimal? Netpresentvalue { get; set; }
        public decimal? Returnoninvestment { get; set; }
        public int? Paybackperiod { get; set; }
        public DateTime? Sumplannedstartdate { get; set; }
        public DateTime? Sumplannedfinishdate { get; set; }
        public decimal? Sumplannedduration { get; set; }
        public decimal? Sumplannedlaborunits { get; set; }
        public decimal? Sumplannednonlaborunits { get; set; }
        public decimal? Sumplannedlaborcost { get; set; }
        public decimal? Sumplannednonlaborcost { get; set; }
        public decimal? Sumplannedexpensecost { get; set; }
        public decimal? Sumplannedmaterialcost { get; set; }
        public decimal? Sumplannedtotalcost { get; set; }
        public string Locationname { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateDimHash { get; set; }
        public DateTime? UpdateDimDate { get; set; }
    }
}
