using System;
using System.Collections.Generic;

#nullable disable

namespace NWC_Dashboard.Models
{
    public partial class UnifierUxlssu
    {
        public int Id { get; set; }
        public string RecordNo { get; set; }
        public string Title { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? UuuRecordLastUpdateDate { get; set; }
        public int? ProcessStatus { get; set; }
        public string Status { get; set; }
        public int? CreatorId { get; set; }
        public int? ProjectId { get; set; }
        public int? AttachCnt { get; set; }
        public int? Reason { get; set; }
        public string SsItem393 { get; set; }
        public string SsItem42 { get; set; }
        public string SsItem41 { get; set; }
        public string SsItem161 { get; set; }
        public string SsItem162 { get; set; }
        public string SsItem392 { get; set; }
        public string SsItem391 { get; set; }
        public string SsItem43 { get; set; }
        public string SsItem163 { get; set; }
        public string PiConsultantName { get; set; }
        public DateTime? SchPmDate { get; set; }
        public int? SchHqhead { get; set; }
        public DateTime? SchContractorName { get; set; }
        public string Ugenclustertname { get; set; }
        public string SsItem271 { get; set; }
        public string SsItem272 { get; set; }
        public string SsItem273 { get; set; }
        public string SsItem173 { get; set; }
        public string SsItem52 { get; set; }
        public string SsItem53 { get; set; }
        public string SsItem171 { get; set; }
        public string SsItem51 { get; set; }
        public string SsItem172 { get; set; }
        public string SsType190 { get; set; }
        public string PiContractorName { get; set; }
        public string SsType199 { get; set; }
        public string SsType197 { get; set; }
        public string SsItem283 { get; set; }
        public string SsType198 { get; set; }
        public string SsType195 { get; set; }
        public string SsType196 { get; set; }
        public string SsType193 { get; set; }
        public string SsType194 { get; set; }
        public string P6InfoTitle { get; set; }
        public string SsType191 { get; set; }
        public string SsItem281 { get; set; }
        public string SsItem282 { get; set; }
        public string SsType192 { get; set; }
        public string SsItem63 { get; set; }
        public string SsItem141 { get; set; }
        public string SsType188 { get; set; }
        public string SsType189 { get; set; }
        public string SsType186 { get; set; }
        public string SsType187 { get; set; }
        public string SsType184 { get; set; }
        public int? SchLeadName { get; set; }
        public string SsType185 { get; set; }
        public string SsItem61 { get; set; }
        public string SsItem371 { get; set; }
        public string SsType182 { get; set; }
        public string SsItem142 { get; set; }
        public string SsType183 { get; set; }
        public string SsItem62 { get; set; }
        public string SsItem372 { get; set; }
        public string SsItem143 { get; set; }
        public string SsType180 { get; set; }
        public string SsItem373 { get; set; }
        public string SsType181 { get; set; }
        public string SsItem251 { get; set; }
        public string SsType179 { get; set; }
        public string SsType177 { get; set; }
        public string SsType178 { get; set; }
        public string SsType175 { get; set; }
        public string SsType176 { get; set; }
        public int? SchScName { get; set; }
        public string SsType173 { get; set; }
        public string SsType174 { get; set; }
        public string SsType171 { get; set; }
        public string SsItem252 { get; set; }
        public string SsItem482 { get; set; }
        public string SsItem481 { get; set; }
        public string SsType172 { get; set; }
        public string SsItem253 { get; set; }
        public string SsType170 { get; set; }
        public string SsItem483 { get; set; }
        public string SsItem72 { get; set; }
        public string SsItem73 { get; set; }
        public string SsType168 { get; set; }
        public string SsType169 { get; set; }
        public string SsType166 { get; set; }
        public string SsType167 { get; set; }
        public string SsType164 { get; set; }
        public string SsType165 { get; set; }
        public string SsType162 { get; set; }
        public string SsType163 { get; set; }
        public string SsItem151 { get; set; }
        public string SsType160 { get; set; }
        public string SsType161 { get; set; }
        public string SsItem71 { get; set; }
        public string SsItem381 { get; set; }
        public string SsItem152 { get; set; }
        public string SsItem382 { get; set; }
        public string SsItem153 { get; set; }
        public string SsItem383 { get; set; }
        public string SsType159 { get; set; }
        public string SsType157 { get; set; }
        public string SsType158 { get; set; }
        public string SsType155 { get; set; }
        public string SsType156 { get; set; }
        public string SsType153 { get; set; }
        public string SsType154 { get; set; }
        public string SsType151 { get; set; }
        public string SsType152 { get; set; }
        public string SsItem261 { get; set; }
        public string SsItem491 { get; set; }
        public string SsType150 { get; set; }
        public string SsItem262 { get; set; }
        public string SsItem263 { get; set; }
        public string SsItem493 { get; set; }
        public string SsItem492 { get; set; }
        public string SsItem83 { get; set; }
        public string SsItem81 { get; set; }
        public string SsItem82 { get; set; }
        public string SsItem503 { get; set; }
        public string SsItem502 { get; set; }
        public string FypNwcCbu { get; set; }
        public string SsType85 { get; set; }
        public string SsType86 { get; set; }
        public string SsType83 { get; set; }
        public string SsType84 { get; set; }
        public string SsType81 { get; set; }
        public string SsType82 { get; set; }
        public string SsType80 { get; set; }
        public string SsType89 { get; set; }
        public string SsType87 { get; set; }
        public string SsType88 { get; set; }
        public string SsItem92 { get; set; }
        public string SsItem93 { get; set; }
        public string SsItem91 { get; set; }
        public string SsItem512 { get; set; }
        public string SsItem511 { get; set; }
        public string SsItem513 { get; set; }
        public DateTime? SchCscheadName { get; set; }
        public string SsType96 { get; set; }
        public string SsType97 { get; set; }
        public string SsType94 { get; set; }
        public string SsType95 { get; set; }
        public string SsType92 { get; set; }
        public string SsType93 { get; set; }
        public string SsType90 { get; set; }
        public string SsType91 { get; set; }
        public string SsItem501 { get; set; }
        public string Uregioncbuname { get; set; }
        public string SsType98 { get; set; }
        public string SsType99 { get; set; }
        public string SsType63 { get; set; }
        public string SsType64 { get; set; }
        public string SsType61 { get; set; }
        public string SsType62 { get; set; }
        public string SsType60 { get; set; }
        public int? SchHeqteam { get; set; }
        public string SsType69 { get; set; }
        public string SsType67 { get; set; }
        public string SsType68 { get; set; }
        public string SsType65 { get; set; }
        public string SsType66 { get; set; }
        public string SsItem182 { get; set; }
        public string SsItem183 { get; set; }
        public DateTime? SchBuschleadName { get; set; }
        public string SsItem181 { get; set; }
        public string SsType74 { get; set; }
        public string SsType75 { get; set; }
        public string SsType72 { get; set; }
        public string SsType73 { get; set; }
        public string SsType70 { get; set; }
        public string SsType71 { get; set; }
        public string SsType78 { get; set; }
        public string SsType79 { get; set; }
        public string SsType76 { get; set; }
        public string SsType77 { get; set; }
        public string SsItem292 { get; set; }
        public string FypNwcRegion { get; set; }
        public string SsItem293 { get; set; }
        public string PsProjectClassification { get; set; }
        public string SsItem291 { get; set; }
        public string SsType41 { get; set; }
        public string SsType42 { get; set; }
        public string SsType40 { get; set; }
        public string SsType49 { get; set; }
        public string SsType47 { get; set; }
        public string SsType48 { get; set; }
        public string SsType45 { get; set; }
        public string SsType46 { get; set; }
        public string SsType43 { get; set; }
        public string SsType44 { get; set; }
        public string SsItem191 { get; set; }
        public string SsItem192 { get; set; }
        public string SsItem193 { get; set; }
        public DateTime? SchCconsultantName { get; set; }
        public string SsType52 { get; set; }
        public string SsType53 { get; set; }
        public string SsType50 { get; set; }
        public string SsType51 { get; set; }
        public string SsType58 { get; set; }
        public string SsType59 { get; set; }
        public string SsType56 { get; set; }
        public string SsType57 { get; set; }
        public string SsType54 { get; set; }
        public string SsType55 { get; set; }
        public string SsType20 { get; set; }
        public string SsType27 { get; set; }
        public string SsType28 { get; set; }
        public string SsType25 { get; set; }
        public string SsType26 { get; set; }
        public string SsType23 { get; set; }
        public string SsType24 { get; set; }
        public string SsType21 { get; set; }
        public int? SchContName { get; set; }
        public string SsType22 { get; set; }
        public string SsItem313 { get; set; }
        public string SsItem311 { get; set; }
        public string SsType18 { get; set; }
        public string SsType19 { get; set; }
        public string SsItem312 { get; set; }
        public string SsType9 { get; set; }
        public int? SchClusterName { get; set; }
        public string SsType30 { get; set; }
        public string SsType31 { get; set; }
        public string SsType38 { get; set; }
        public string SsType39 { get; set; }
        public string SsType36 { get; set; }
        public string SsType37 { get; set; }
        public string SsType34 { get; set; }
        public string SsType35 { get; set; }
        public string SsType32 { get; set; }
        public string SsType33 { get; set; }
        public string SsItem423 { get; set; }
        public string Ugenprojectnumber { get; set; }
        public string SsType29 { get; set; }
        public string SsItem422 { get; set; }
        public string SsItem421 { get; set; }
        public string SsItem8 { get; set; }
        public string SsItem9 { get; set; }
        public string SsItem6 { get; set; }
        public string SsItem7 { get; set; }
        public string SsItem4 { get; set; }
        public string SsItem5 { get; set; }
        public string SsItem2 { get; set; }
        public string SsItem3 { get; set; }
        public string SsItem1 { get; set; }
        public string PsProjectType { get; set; }
        public string SsItem322 { get; set; }
        public string SsItem323 { get; set; }
        public string SsItem321 { get; set; }
        public string SchAttach1 { get; set; }
        public int? SchPm { get; set; }
        public string SsType16 { get; set; }
        public string SsType17 { get; set; }
        public string SsType14 { get; set; }
        public string SsType15 { get; set; }
        public string SsType12 { get; set; }
        public string SsType13 { get; set; }
        public string SsType10 { get; set; }
        public string SsType11 { get; set; }
        public string SsItem203 { get; set; }
        public string SsItem433 { get; set; }
        public string SsItem432 { get; set; }
        public string SsItem201 { get; set; }
        public string SsItem431 { get; set; }
        public string SsItem202 { get; set; }
        public string SsItem521 { get; set; }
        public DateTime? SchHqschName { get; set; }
        public string SsItem523 { get; set; }
        public string SsItem522 { get; set; }
        public DateTime? SchHqsctName { get; set; }
        public string SsItem402 { get; set; }
        public string SsItem401 { get; set; }
        public string SsItem403 { get; set; }
        public string SsItem301 { get; set; }
        public string SsItem302 { get; set; }
        public string SsItem303 { get; set; }
        public string SsType4 { get; set; }
        public string SsType3 { get; set; }
        public string SsType2 { get; set; }
        public string SsType1 { get; set; }
        public string SsType8 { get; set; }
        public string SsType7 { get; set; }
        public string SsType6 { get; set; }
        public string SsType5 { get; set; }
        public string SsItem411 { get; set; }
        public string SsItem413 { get; set; }
        public string SsItem412 { get; set; }
        public string SsItem50 { get; set; }
        public string SsItem524 { get; set; }
        public string SsItem514 { get; set; }
        public string SsItem351 { get; set; }
        public string SsType148 { get; set; }
        public string SsType149 { get; set; }
        public string SsItem352 { get; set; }
        public string SsType146 { get; set; }
        public string SsItem123 { get; set; }
        public DateTime? Ugenprojenddatedo { get; set; }
        public string SsType147 { get; set; }
        public string SsItem122 { get; set; }
        public string SsItem121 { get; set; }
        public string SsType144 { get; set; }
        public string SsType145 { get; set; }
        public string SsType142 { get; set; }
        public string SsType143 { get; set; }
        public string SsType140 { get; set; }
        public string SsType141 { get; set; }
        public string SsItem353 { get; set; }
        public DateTime? UuuCreationDate { get; set; }
        public string SsType139 { get; set; }
        public string SsItem231 { get; set; }
        public string SsType137 { get; set; }
        public string SsItem232 { get; set; }
        public string SsItem462 { get; set; }
        public string SsItem461 { get; set; }
        public string SsType138 { get; set; }
        public string SsItem233 { get; set; }
        public string SsType135 { get; set; }
        public string SsType136 { get; set; }
        public string SsType133 { get; set; }
        public string SsType134 { get; set; }
        public string SsType131 { get; set; }
        public string SsType132 { get; set; }
        public string SsType130 { get; set; }
        public string SsItem463 { get; set; }
        public string SsItem30 { get; set; }
        public string SsType119 { get; set; }
        public string SsItem36 { get; set; }
        public string SsType128 { get; set; }
        public string SubmissionType { get; set; }
        public string SsItem35 { get; set; }
        public string SsType129 { get; set; }
        public string SsItem38 { get; set; }
        public string SsItem131 { get; set; }
        public string SsType126 { get; set; }
        public string SsItem37 { get; set; }
        public string SsType127 { get; set; }
        public string SsItem361 { get; set; }
        public string SsItem132 { get; set; }
        public string SsItem32 { get; set; }
        public string SsType124 { get; set; }
        public string SsItem31 { get; set; }
        public string SsType125 { get; set; }
        public string SsItem34 { get; set; }
        public string SsType122 { get; set; }
        public string SsItem33 { get; set; }
        public string SsType123 { get; set; }
        public string SsItem11 { get; set; }
        public string SsType120 { get; set; }
        public string SsType121 { get; set; }
        public string SsItem13 { get; set; }
        public string SsItem12 { get; set; }
        public string SsItem362 { get; set; }
        public string SsItem133 { get; set; }
        public string SsItem39 { get; set; }
        public string SsItem363 { get; set; }
        public string Ugenprojectname { get; set; }
        public string SsItem414 { get; set; }
        public string SsItem40 { get; set; }
        public string SsType108 { get; set; }
        public string SsType109 { get; set; }
        public string SsItem47 { get; set; }
        public string SsType117 { get; set; }
        public string SsItem46 { get; set; }
        public string SsType118 { get; set; }
        public string SsItem49 { get; set; }
        public string SsType115 { get; set; }
        public string SsItem241 { get; set; }
        public string SsItem471 { get; set; }
        public string SsItem48 { get; set; }
        public string SsItem242 { get; set; }
        public string SsType116 { get; set; }
        public DateTime? SchBuconsName { get; set; }
        public string SsItem434 { get; set; }
        public string SsType113 { get; set; }
        public string SsItem424 { get; set; }
        public string SsType114 { get; set; }
        public string SsItem45 { get; set; }
        public string SsType111 { get; set; }
        public string SsItem44 { get; set; }
        public string SsType112 { get; set; }
        public string SsType110 { get; set; }
        public string SsItem243 { get; set; }
        public string SsItem473 { get; set; }
        public DateTime? UuuProjectStartDate { get; set; }
        public string SsItem472 { get; set; }
        public string SsItem14 { get; set; }
        public string SsItem101 { get; set; }
        public string SsItem331 { get; set; }
        public string SsType106 { get; set; }
        public string SsItem134 { get; set; }
        public string SsType107 { get; set; }
        public string SsItem332 { get; set; }
        public string SsItem16 { get; set; }
        public string SsType104 { get; set; }
        public string SsItem333 { get; set; }
        public string SsItem15 { get; set; }
        public string SsType105 { get; set; }
        public string SsItem10 { get; set; }
        public string SsType102 { get; set; }
        public string SsType103 { get; set; }
        public string SsItem124 { get; set; }
        public string SsType100 { get; set; }
        public string SsItem103 { get; set; }
        public string SsItem111 { get; set; }
        public string SsType101 { get; set; }
        public string SsItem102 { get; set; }
        public string SsItem22 { get; set; }
        public string SsItem21 { get; set; }
        public string SsItem18 { get; set; }
        public string SsItem17 { get; set; }
        public string SsItem23 { get; set; }
        public string SsItem19 { get; set; }
        public string SsType207 { get; set; }
        public string SsType208 { get; set; }
        public string SsItem25 { get; set; }
        public string SsItem212 { get; set; }
        public string SsItem442 { get; set; }
        public string SsItem24 { get; set; }
        public string SsItem441 { get; set; }
        public string SsItem213 { get; set; }
        public string SsItem27 { get; set; }
        public string SsItem26 { get; set; }
        public string SsItem443 { get; set; }
        public string SsItem211 { get; set; }
        public string SsItem20 { get; set; }
        public string SsItem234 { get; set; }
        public string SsItem221 { get; set; }
        public string SsItem2111 { get; set; }
        public string SsItem29 { get; set; }
        public string SsItem28 { get; set; }
        public int? SchBuconName { get; set; }
        public string SsType205 { get; set; }
        public string SsItem341 { get; set; }
        public string SsType206 { get; set; }
        public string SsType203 { get; set; }
        public string SsItem342 { get; set; }
        public string SsType204 { get; set; }
        public string SsItem343 { get; set; }
        public string SsType201 { get; set; }
        public string SsType202 { get; set; }
        public string SsItem113 { get; set; }
        public string SsItem112 { get; set; }
        public string SsItem1111 { get; set; }
        public string SsType200 { get; set; }
        public string SsItem314 { get; set; }
        public string SsItem334 { get; set; }
        public string SsItem324 { get; set; }
        public string SsItem2211 { get; set; }
        public string SsItem451 { get; set; }
        public string SsItem222 { get; set; }
        public string SsItem223 { get; set; }
        public string SsItem453 { get; set; }
        public string SsItem452 { get; set; }
    }
}
