using System;
using System.Collections.Generic;

#nullable disable

namespace NWC_Dashboard.Models
{
    public partial class UnifierUcox
    {
        public int Id { get; set; }
        public string RecordNo { get; set; }
        public string Title { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? UuuRecordLastUpdateDate { get; set; }
        public int? ProcessStatus { get; set; }
        public string Status { get; set; }
        public int? CreatorId { get; set; }
        public int? ProjectId { get; set; }
        public int? AttachCnt { get; set; }
        public int? Reason { get; set; }
        public decimal? Currencyrate { get; set; }
        public decimal? UsdCurrencyrate { get; set; }
        public int? Xid { get; set; }
        public string Uvefaxtb16 { get; set; }
        public string Ugendescriptionmtl4000 { get; set; }
        public decimal? Ugenlineitemcountda { get; set; }
        public decimal? Ucoamountofthiscoca { get; set; }
        public string VenSuppnum { get; set; }
        public string Uveprimarycontacttb64 { get; set; }
        public string UuuUserEmail { get; set; }
        public decimal? Ucoconumberda { get; set; }
        public string Upocontracttypepd { get; set; }
        public string Ugencontractrnd { get; set; }
        public string Ugencitytxt50 { get; set; }
        public string UuuDmPublishPath { get; set; }
        public decimal? Ucoamountprevtoca { get; set; }
        public int? ChProjectContractor { get; set; }
        public decimal? Uconcontractbalanceca { get; set; }
        public string PiConsultantName { get; set; }
        public DateTime? UuuCreationDate { get; set; }
        public string CoSeqNo { get; set; }
        public string Uvephonetb64 { get; set; }
        public string CoConsOpnion { get; set; }
        public string ChPurchaseOrder { get; set; }
        public int? Uveminoritybuscb { get; set; }
        public decimal? Ucoautocreateflagda { get; set; }
        public string Uvevendornametb50 { get; set; }
        public string Ugenprojectnumber { get; set; }
        public string FypNwcCbu { get; set; }
        public string Ugenclustertname { get; set; }
        public DateTime? BcProjectStartDate { get; set; }
        public string VendorType { get; set; }
        public string Ugenchangereasonmtl4000 { get; set; }
        public int? ChProjectConsultant { get; set; }
        public string ChProjectDurationElapse { get; set; }
        public decimal? ChProjectRequestChangeV { get; set; }
        public decimal? OmCost { get; set; }
        public string PsProjectType { get; set; }
        public string ChProjectAfterApproved { get; set; }
        public decimal? CVatTotal { get; set; }
        public decimal? Ucopotentialcontactamtca { get; set; }
        public decimal? ChContractualValue { get; set; }
        public int? Ugenactivitydpk { get; set; }
        public decimal? ChPercentageCompletion { get; set; }
        public string CoTitle { get; set; }
        public string Ugenzipcodetxt16 { get; set; }
        public string Uveemailtb120 { get; set; }
        public DateTime? ChProjectDateAfterReque { get; set; }
        public string Ugenaddress3txt120 { get; set; }
        public string Ugenprojectname { get; set; }
        public string Ucoreasonpd { get; set; }
        public string PiContractorName { get; set; }
        public decimal? Uconapprovedchangesamtqe { get; set; }
        public string Uregioncbuname { get; set; }
        public decimal? Ucopendingchangesqe { get; set; }
        public int? Ucoconumberia { get; set; }
        public decimal? Untpcontractamtca { get; set; }
        public DateTime? Ugenp6plannedstartdop { get; set; }
        public string Ugencontactnametb { get; set; }
        public string Ugenaddress2txt120 { get; set; }
        public string Upocontracttermsmlt4000 { get; set; }
        public decimal? CountOfChangeOrders { get; set; }
        public int? CoIntopd { get; set; }
        public decimal? ChPercentageProject { get; set; }
        public decimal? Ugenconosumda { get; set; }
        public string ChTransactiontNo { get; set; }
        public DateTime? CoReqdate { get; set; }
        public string Ugenscopeofworkmtl4000 { get; set; }
        public decimal? Ucocountackquotesnqb { get; set; }
        public string VenSuppnam { get; set; }
        public string ChTotalTime { get; set; }
        public decimal? ChangeOrderCountValue { get; set; }
        public int? Refid { get; set; }
        public string CoName { get; set; }
        public decimal? ChProjectCurrentValue { get; set; }
        public int? Ugenbpassignee { get; set; }
        public decimal? Uconactualstodateca { get; set; }
        public string Ugenaddress1txt120 { get; set; }
        public decimal? Ucoquoteresrevda { get; set; }
        public string Ucobdgtchngreqapptb { get; set; }
        public DateTime? BcProjectEndDate { get; set; }
        public string FypNwcRegion { get; set; }
        public decimal? Uconrevisedcontctamtca { get; set; }
        public string Ugencountrypd { get; set; }
        public DateTime? Ugendatecalcdop { get; set; }
        public string PsProjectClassification { get; set; }
        public DateTime? ChProjectEndDate { get; set; }
        public decimal? ChProjectAfterRequiredV { get; set; }
        public DateTime? ChProjectDateAfterAppro { get; set; }
        public decimal? CVat { get; set; }
        public int? CoIntdp { get; set; }
        public string Upocontractdescmlt4000 { get; set; }
        public int? Uxpcpcrecordnobp { get; set; }
        public DateTime? Ugenp6plannedfinishdop { get; set; }
        public decimal? Amount { get; set; }
        public decimal? Ugenp6plannedcostca { get; set; }
        public DateTime? CoReqlettdate { get; set; }
        public int? Uvewomanownedcb { get; set; }
        public DateTime? Ugentodaydatedop { get; set; }
        public int? Uvedisadvantagedbuscb { get; set; }
        public decimal? Uconoriginalcontrctamtca { get; set; }
        public string CoLettno { get; set; }
        public int? Ucoscheduleimpactdaysia { get; set; }
        public int? Currencyid { get; set; }
        public string Uvevendoridtb16 { get; set; }
        public string Ugenstatepd { get; set; }
        public string Uconcontractnumbertxt16 { get; set; }
        public int? IaScN { get; set; }
        public DateTime? ChoHqGmDate { get; set; }
        public DateTime? ChoContractorDate { get; set; }
        public DateTime? ChoClusterSeniorgmd { get; set; }
        public DateTime? ChoNaHqDate { get; set; }
        public DateTime? ChoCreationDate { get; set; }
        public DateTime? ChoSupervisinconsDate { get; set; }
        public int? ChoNaCluster { get; set; }
        public DateTime? ChoNaClusterDate { get; set; }
        public int? CoUserPick { get; set; }
        public DateTime? ChoSchedulecontrolGmd { get; set; }
        public int? ChoHqGm { get; set; }
        public DateTime? ChoTsGmd2 { get; set; }
        public DateTime? ChoTsVpd2 { get; set; }
        public int? ChoSchedulecontrolGm { get; set; }
        public int? ChoClusterProjectsgm { get; set; }
        public int? ChoTsGm { get; set; }
        public int? ChoAthuPerson { get; set; }
        public DateTime? ChoNwcpmDate { get; set; }
        public int? ChoTsVp { get; set; }
        public int? CoCreator { get; set; }
        public DateTime? ChoConManagerDate { get; set; }
        public int? ChoClusterSeniorgm { get; set; }
        public string UuuUserCompany { get; set; }
        public int? ChoCcontractManger { get; set; }
        public string BoqDescion { get; set; }
        public DateTime? ChoTsDirectorDate { get; set; }
        public int? NcrNwcPm { get; set; }
        public int? ChoTsDirector { get; set; }
        public DateTime? ChoClusterProjectsgmd { get; set; }
        public int? ChoCreator { get; set; }
        public int? IaCoN { get; set; }
        public DateTime? ChoSupplyChaind2 { get; set; }
        public int? ChoNaHq { get; set; }
        public int? ChoSupplyChain { get; set; }
        public DateTime? ChoAthuPersonDate { get; set; }
        public string FypNwcProjectType2 { get; set; }
        public decimal? BcProjectEstimatedCosts { get; set; }
        public string FypNwcCity { get; set; }
    }
}
