using System;
using System.Collections.Generic;

#nullable disable

namespace NWC_Dashboard.Models
{
    public partial class UnifierUsP
    {
        public int Pid { get; set; }
        public int? PiContractduration { get; set; }
        public string BcPreviousStudies { get; set; }
        public string PiCommitteeformationdate { get; set; }
        public decimal? PiSiteProcessingPeriod { get; set; }
        public string BcStrategicProject { get; set; }
        public decimal? BcRatioAfterProject { get; set; }
        public int? PiPasseddurationpercentage { get; set; }
        public string FypNwcSubstitution { get; set; }
        public string PiConsultantName { get; set; }
        public string PiProjectlocation { get; set; }
        public decimal? FypEstimatedCost { get; set; }
        public string PiNameSignature { get; set; }
        public string PiMobileSupervisor { get; set; }
        public int? UuuLocation { get; set; }
        public string UuuAddressCode { get; set; }
        public DateTime? PiDrawdateg { get; set; }
        public string BcCostChart { get; set; }
        public string BcFinalFinancial { get; set; }
        public int? BcSupplyChain { get; set; }
        public string Ugenprojectnumber { get; set; }
        public int? PiHomeconnectionsno { get; set; }
        public int? PiModificationduration { get; set; }
        public string PiStopNumber { get; set; }
        public string PiSchedulereceiptdate { get; set; }
        public string PiPositionSignatureHolde { get; set; }
        public string UuuLatitude { get; set; }
        public string PiProjectConsultantEngin { get; set; }
        public int? BcCreatingNewJobs { get; set; }
        public decimal? OmCost { get; set; }
        public int? EnjaPickRef { get; set; }
        public string BcProgram { get; set; }
        public string PsProjectType { get; set; }
        public decimal? PiIncreasesInContractVa { get; set; }
        public string PiContractenddate { get; set; }
        public string PiNwcmewaclassification { get; set; }
        public DateTime? PiEndDateTechnicalAnaly { get; set; }
        public decimal? BcRatioAfter { get; set; }
        public int? PiTotalplansno { get; set; }
        public string BcReliability { get; set; }
        public string BcImRisks { get; set; }
        public string PiContractorName { get; set; }
        public string FypEntityId { get; set; }
        public int? PiPlannedpercentage { get; set; }
        public int? PiDelay { get; set; }
        public string PiContractNumberDepartme { get; set; }
        public string BcVolume { get; set; }
        public string PiConsultantcontract { get; set; }
        public string PiReviews { get; set; }
        public DateTime? PiDateOpeningEnvelopes { get; set; }
        public DateTime? PiIrsigningdateg { get; set; }
        public string PiProjectlastmodifieddate { get; set; }
        public int? PiPeriodnelineslengths { get; set; }
        public string PiIrsigningdate { get; set; }
        public int? PiContractor { get; set; }
        public decimal? BcEstimatedCosts { get; set; }
        public decimal? BcOperationalCosts { get; set; }
        public DateTime? PiEndDateOpeningEnvelop { get; set; }
        public string PiReasonForExtension { get; set; }
        public string FypNwcCluster { get; set; }
        public int? PiContractextenduration { get; set; }
        public decimal? BcProjectRatio { get; set; }
        public string BcNameProgram { get; set; }
        public string BcCostMechanism { get; set; }
        public string PiResponsible { get; set; }
        public decimal? BcProjectEstimatedCosts { get; set; }
        public string PiContractsigningdate { get; set; }
        public decimal? Ugenestbudgetca { get; set; }
        public int? PiActualpercentage { get; set; }
        public string PiSupervisorNumber { get; set; }
        public string Description { get; set; }
        public int? BcCostChartAtt { get; set; }
        public string PiPurchaseno { get; set; }
        public string BcProjectInitiatives { get; set; }
        public string UuuIntP6ProjectId { get; set; }
        public DateTime? PiSchedulereceiptdateg { get; set; }
        public decimal? PiValueWorksExecuted { get; set; }
        public string BcCurrentVolume { get; set; }
        public int? UuuAdministrator { get; set; }
        public DateTime? PiContractorrequestdateg { get; set; }
        public int? PiPeriodhomeconnectionsno { get; set; }
        public string PiWithdrawal { get; set; }
        public string BcSizeProject { get; set; }
        public decimal? PiCumulative { get; set; }
        public string BcInitiativeName { get; set; }
        public decimal? PiProjectestimatedvalue { get; set; }
        public DateTime? PiEndDateScreeningFers { get; set; }
        public string FypProjectSn { get; set; }
        public string Ugenstatepd { get; set; }
        public DateTime? PiDateNotificationDirect { get; set; }
        public string FypNwcProjectType2 { get; set; }
        public string BcImPlan { get; set; }
        public int? BcCostStudyAtt { get; set; }
        public string FypNwcProjectType { get; set; }
        public decimal? BcRatioBefore { get; set; }
        public DateTime? Ugenprojenddatedo { get; set; }
        public int? PiDurationContract { get; set; }
        public string PiContsitehandoverdate { get; set; }
        public string Ugencitytxt50 { get; set; }
        public string PiDescriptionCompetition { get; set; }
        public decimal? BcRevenueIncrease { get; set; }
        public int? PiActualandplanneddifferen { get; set; }
        public int? PiModifiedplannedpercent { get; set; }
        public string PiSuspensionreason { get; set; }
        public string PiProjectstatus { get; set; }
        public string FypNwcPackage { get; set; }
        public DateTime? PiContractenddateg { get; set; }
        public string PiSupervisorEmail { get; set; }
        public string FypNwcCbu { get; set; }
        public string BcStrategicConsensus { get; set; }
        public DateTime? BcProjectStartDate { get; set; }
        public string Ugenprojecttypepd { get; set; }
        public DateTime? PiModifiedcontenddateg { get; set; }
        public string BcProjectPrograms { get; set; }
        public int? FypProjectPk { get; set; }
        public decimal? BcCostSupervision { get; set; }
        public string PiBudgetitemname { get; set; }
        public string Ugenzipcodetxt16 { get; set; }
        public DateTime? PiFinalPlannedReceipt { get; set; }
        public string UuuIntScheduleType { get; set; }
        public string Piopcontractno { get; set; }
        public string PiContractCopy { get; set; }
        public string Ugenaddress3txt120 { get; set; }
        public string Ugenprojectname { get; set; }
        public string PiPono { get; set; }
        public decimal? BcDesignCost { get; set; }
        public DateTime? PiLastExtensionFrom { get; set; }
        public string BcAssessingOptions { get; set; }
        public string PiContractStartsFrom { get; set; }
        public DateTime? PiCommitteeformationdateg { get; set; }
        public DateTime? PiAwarddateg { get; set; }
        public DateTime? PiLastExtensionTo { get; set; }
        public string Ugenaddress2txt120 { get; set; }
        public DateTime? UuuProjectStartDate { get; set; }
        public decimal? PiContractvalue { get; set; }
        public string BcScopeProject { get; set; }
        public string ShellTemplateName { get; set; }
        public DateTime? PiReleaseDate { get; set; }
        public DateTime? PiSuspensiondateg { get; set; }
        public int? PiNelineslengths { get; set; }
        public string PiDescriptionPeriod { get; set; }
        public int? BcNumberPosts { get; set; }
        public string BcCurrentSize { get; set; }
        public string PiModifiedcontenddate { get; set; }
        public string FypNwcContractStatus { get; set; }
        public int? BcImRisksAtt { get; set; }
        public string BcProjectObjectives { get; set; }
        public string PiAdministrativeauthority { get; set; }
        public int? BcNumbeBeneficiaries { get; set; }
        public string BcNeedProject { get; set; }
        public string PiSubtractionStatus { get; set; }
        public string PiContractorrequestdate { get; set; }
        public decimal? PiModifiedcontractvalue { get; set; }
        public int? BcNumberJobs { get; set; }
        public int? PiConsultant { get; set; }
        public string PiResponsibleDetail { get; set; }
        public int? BcImPlanAtt { get; set; }
        public string Ugenaddress1txt120 { get; set; }
        public int? FypPeriodPk { get; set; }
        public int? UuuShellStatus { get; set; }
        public string FypNwcProjectClassificat { get; set; }
        public string PiRequestingParty { get; set; }
        public DateTime? PiLastDate { get; set; }
        public DateTime? BcProjectEndDate { get; set; }
        public string Ugencountrypd { get; set; }
        public string FypNwcRegion { get; set; }
        public string PsProjectClassification { get; set; }
        public string BcFinalStrategic { get; set; }
        public DateTime? PiPlannedPrimaryReceipt { get; set; }
        public string BcSizeGap { get; set; }
        public string BcGap { get; set; }
        public string PiAdvertiser { get; set; }
        public string PiContractNotes { get; set; }
        public string UuuLongitude { get; set; }
        public int? BcScheduleMonth { get; set; }
        public string BcFinalEconomic { get; set; }
        public string PiBudgetprojectno { get; set; }
        public decimal? PiContractReductions { get; set; }
        public string BcOtherBenefits { get; set; }
        public int? FypProjectPkRef { get; set; }
        public string PiDescriptionDurationCon { get; set; }
        public DateTime? PiContsitehandoverdateg { get; set; }
        public string PiContractstatus { get; set; }
        public string PiSector { get; set; }
        public decimal? BcMonthlyProjectSr { get; set; }
        public int? BcProjectPlan { get; set; }
        public int? BcProjectCostNo { get; set; }
        public int? PiTotalInformalExtension { get; set; }
        public string BcCostStudy { get; set; }
        public decimal? PiCumulativeActual { get; set; }
        public string PiSupervisorName { get; set; }
        public DateTime? PiContractsigningdateg { get; set; }
        public string FypNwcSpecialProgram { get; set; }
        public string UuuIntegratedWith { get; set; }
        public string UuuLat { get; set; }
        public string UuuLong { get; set; }
        public decimal? ProInfoWithdYears { get; set; }
        public int? ProInfoWithdDiff { get; set; }
        public string ProInfoReasonSusp { get; set; }
        public string PhasesProject { get; set; }
        public string ProInfoSuspRespAuth { get; set; }
        public DateTime? ProInfoWithdToday { get; set; }
        public DateTime? ProInfoTodaysus { get; set; }
        public decimal? ProInfoYofsusp { get; set; }
        public string PiContractstatus2 { get; set; }
        public DateTime? NewHandoverDate { get; set; }
        public string PiContractstatus3 { get; set; }
        public string PiContractstatus1 { get; set; }
        public string BcFinancing { get; set; }
        public int? ProInfoSusDiff { get; set; }
        public string ContractSt1 { get; set; }
        public string FypNwcCity { get; set; }
        public DateTime? ChPlannedE { get; set; }
        public DateTime? ChPlannedS { get; set; }
        public string BcStrategic { get; set; }
        public int? CmpConName { get; set; }
    }
}
